version: '3.8'

services:
  # Service 1: Redis (the message queue)
  redis:
    image: redis:7-alpine  # Official Redis image
    ports:
      - "6379:6379"  # Make it accessible on your computer too
    command: >
      redis-server
      --requirepass ${REDIS_PASSWORD}
      --bind 0.0.0.0
      --protected-mode no
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
      --save 900 1
      --save 300 10
      --save 60 10000
      --appendonly yes
    env_file:
      - .env  # ← Reads REDIS_PASSWORD from .env
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  indexer:
    image: my-indexer
    depends_on:
      redis:
        condition: service_healthy  # Wait for Redis to be healthy
    volumes:
      - ./shared/database:/app/shared/database # Share database
    build: 
      context: .
      dockerfile: indexer/Dockerfile
    env_file:
      - .env  # ← Load from .env file
    
    environment:
      - REDIS_HOST=redis  # Tell it where Redis is
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - PYTHONUNBUFFERED=1  # Ensure real-time logging
      - DB_PATH=${DB_PATH}  # Path to the database
      - TIMEOUT=60  # DB timeout in seconds
    networks:
      - app-network
    restart: unless-stopped


# Create a network for all services
networks:
  app-network:
    driver: bridge