version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "${API_PORT}:5000"
    volumes:
      - ./shared/database:/app/shared/database # Share database
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1  # Ensure real-time logging
      - DB_PATH=${DB_PATH}  # Path to the database