SEPARATOR_FOR_NAME="/"
SEPARATOR_FOR_VERSION="@"
SEPARATOR_FOR_QUALIFIER="?"
SEPARATOR_BETWEEN_KEY_AND_VALUE="="
SEPARATOR_BETWEEN_QUALIFIERS="&"
SEPARATOR_FOR_SUBPATH="#"
SEPARATOR_FOR_SCHEME=":"
PURL_PREFIX="pkg"

MAX_PURL_LENGTH=4096



