SEPARATOR_FOR_NAME="/"
SEPARATOR_FOR_VERSION="@"
SEPARATOR_FOR_QUALIFIER="?"
SEPARATOR_FOR_SUBPATH="#"
PURL_PREFIX="pkg:"

#Number of components excluding namespace
PURL_MINIMUM_NUMBER_OF_COMPONENTS=2
#Number of components including namespace
PURL_MAXIMUM_NUMBER_OF_COMPONENTS=3

PURL_TITLE_INDEX=0
PURL_NAMESPACE_INDEX=1
PURL_PACKAGE_INDEX=-1
PACKAGE_NAME_INDEX=0
PACKAGE_VERSION_INDEX=1
PACKAGE_QUALIFIER_INDEX=2
PACKAGE_SUBPATH_INDEX=3