name: Testing

on:
    push:
    pull_request:

jobs:
    run-tests:
        strategy:
            fail-fast: false
            matrix:
                os: [macos-latest]
        name: Test
        runs-on: ${{ matrix.os }}

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Setup
              uses: actions/setup-python@v4
              with:
                python-version: '3.9'

            - name: Run Tests
              run: python -m unittest discover -s purl_parser -p "test_*.py"